In [ ]:
1. Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np
  
X = [[1,3,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) + np.array(Y)
 
print(result)

[[10 11 10]
 [10 10 10]
 [10 10 10]]


In [11]:
import numpy as np

R1 = int(input("Enter the number of rows for matrix1:"))
C1 = int(input("Enter the number of columns for matrix1:"))

print("Enter the entries in a single line (separated by space): ")

entries = list(map(int, input().split()))

matrix1 = np.array(entries).reshape(R1, C1)
print(matrix1)

R2 = int(input("Enter the number of rows for matrix2:"))
C2 = int(input("Enter the number of columns for matrix2:"))

print("Enter the entries in a single line (separated by space): ")

entries = list(map(int, input().split()))

matrix2 = np.array(entries).reshape(R2, C2)
print(matrix2)

result = np.array(matrix1) + np.array(matrix2)
 
print("Sum of 2 matrix is : ")
print(result)


Enter the number of rows for matrix1:2
Enter the number of columns for matrix1:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]
Enter the number of rows for matrix2:2
Enter the number of columns for matrix2:2
Enter the entries in a single line (separated by space): 
5 6 7 8
[[5 6]
 [7 8]]
Sum of 2 matrix is : 
[[ 6  8]
 [10 12]]


In [ ]:
2. Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np
  
X = [[1,3,3],
    [4 ,5,6],
    [7 ,8,9]]
  
Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]
 
result = np.array(X) * np.array(Y)
 
print(result)

[[ 9 24 21]
 [24 25 24]
 [21 16  9]]


In [13]:
import numpy as np

R1 = int(input("Enter the number of rows for matrix1:"))
C1 = int(input("Enter the number of columns for matrix1:"))

print("Enter the entries in a single line (separated by space): ")

entries = list(map(int, input().split()))

matrix1 = np.array(entries).reshape(R1, C1)
print(matrix1)

R2 = int(input("Enter the number of rows for matrix2:"))
C2 = int(input("Enter the number of columns for matrix2:"))

print("Enter the entries in a single line (separated by space): ")

entries = list(map(int, input().split()))

matrix2 = np.array(entries).reshape(R2, C2)
print(matrix2)

result = np.array(matrix1) * np.array(matrix2)
 
print("Mulitiplication of 2 matrix is : ")
print(result)

Enter the number of rows for matrix1:2
Enter the number of columns for matrix1:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]
Enter the number of rows for matrix2:2
Enter the number of columns for matrix2:2
Enter the entries in a single line (separated by space): 
5 6 7 8
[[5 6]
 [7 8]]
Mulitiplication of 2 matrix is : 
[[ 5 12]
 [21 32]]


In [ ]:
3. Write a Python Program to Transpose a Matrix?

In [14]:
import numpy as np

R1 = int(input("Enter the number of rows for matrix:"))
C1 = int(input("Enter the number of columns for matrix:"))

print("Enter the entries in a single line (separated by space): ")

entries = list(map(int, input().split()))

matrix1 = np.array(entries).reshape(R1, C1)
print(matrix1)

result =matrix1.transpose()
 
print("Transpose of matrix is : ")
print(result)


Enter the number of rows for matrix:2
Enter the number of columns for matrix:2
Enter the entries in a single line (separated by space): 
1 2 3 4
[[1 2]
 [3 4]]
Transpose of matrix is : 
[[1 3]
 [2 4]]


In [ ]:
4. Write a Python Program to Sort Words in Alphabetic Order?

In [5]:
my_str = input("Enter a string: ")  
my_str=my_str.lower()
words = my_str.split()  
words.sort()  
for word in words:  
   print(word)  

Enter a string: Hello this Is an Example With cased letters
an
cased
example
hello
is
letters
this
with


In [ ]:
5. Write a Python Program to Remove Punctuation From a String?

In [6]:
import re
my_str = input("Enter a string: ")  
new_string = re.sub(r'[^\w\s]', '', my_str)
print(new_string)

Enter a string: Hello, welcome to my blog! :
Hello welcome to my blog 


In [10]:

import string

my_str = input("Enter a string: ")  
print("The original string is : " + my_str)

for i in string.punctuation:
    my_str=my_str.replace(i, '')
    
print("The string after punctuation filter : " + my_str)

Enter a string: Hello, welcome to my blog! :
The original string is : Hello, welcome to my blog! :
The string after punctuation filter : Hello welcome to my blog 
